# Generated by Django 4.2.18 on 2025-02-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification time"
                    ),
                ),
                (
                    "validity_period_start",
                    models.DateTimeField(verbose_name="Valid from"),
                ),
                (
                    "validity_period_end",
                    models.DateTimeField(verbose_name="Valid until"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("ALERT", "Alert"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=8,
                        verbose_name="Notification type",
                    ),
                ),
                (
                    "title_fi",
                    models.CharField(max_length=200, verbose_name="Title (Finnish)"),
                ),
                (
                    "title_sv",
                    models.CharField(max_length=200, verbose_name="Title (Swedish)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (English)"),
                ),
                ("content_fi", models.TextField(verbose_name="Content (Finnish)")),
                ("content_sv", models.TextField(verbose_name="Content (Swedish)")),
                ("content_en", models.TextField(verbose_name="Content (English)")),
                (
                    "external_url_fi",
                    models.URLField(blank=True, verbose_name="External URL (Finnish)"),
                ),
                (
                    "external_url_sv",
                    models.URLField(blank=True, verbose_name="External URL (Swedish)"),
                ),
                (
                    "external_url_en",
                    models.URLField(blank=True, verbose_name="External URL (English)"),
                ),
                (
                    "external_url_title_fi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="External URL title (Finnish)",
                    ),
                ),
                (
                    "external_url_title_sv",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="External URL title (Swedish)",
                    ),
                ),
                (
                    "external_url_title_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="External URL title (English)",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
            },
        ),
    ]
